services:
  - type: web
    name: smart-research-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://smart-research-answering-backend.up.railway.app  //will change this to what maryyam will give me the url of backend